// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BreadthBin 涨跌分布档位。Level 为涨跌幅档（-11 ~ 11，负数下跌；±11 为 >10% 即涨/跌停档）。
 */
export class BreadthBin {
    /**
     * 档位
     */
    "level": number;

    /**
     * 家数
     */
    "count": number;

    /** Creates a new BreadthBin instance. */
    constructor($$source: Partial<BreadthBin> = {}) {
        if (!("level" in $$source)) {
            this["level"] = 0;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BreadthBin instance from a string or object.
     */
    static createFrom($$source: any = {}): BreadthBin {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BreadthBin($$parsedSource as Partial<BreadthBin>);
    }
}

/**
 * FundDetail 基金详情聚合数据。
 */
export class FundDetail {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 基金类型
     */
    "type": string;

    /**
     * 实际申购费率（%）
     */
    "rate": string;

    /**
     * 最小申购金额
     */
    "minPurchase": string;

    /**
     * 单位净值走势
     */
    "netWorthTrend": TrendPoint[];

    /**
     * 累计净值走势
     */
    "acWorthTrend": TrendPoint[];

    /**
     * 历史最大回撤（%，由单位净值序列计算，负值如 -23.45）
     */
    "maxDrawdown": number;

    /**
     * 阶段涨幅（近1月/近3月/近6月/近1年/近3年/成立来等）
     */
    "periodReturns": PeriodReturn[];

    /**
     * 前十重仓股
     */
    "holdings": Holding[];

    /**
     * 现任基金经理
     */
    "managers": ManagerInfo[];

    /**
     * 数据抓取时间（Unix 秒）
     */
    "fetchedAt": number;

    /**
     * 标签信息（来自移动端详情接口）
     * 基金公司
     */
    "company": string;

    /**
     * 跟踪指数（指数型基金）
     */
    "indexName": string;

    /**
     * 风险等级（1-5）
     */
    "riskLevel": string;

    /**
     * 成立日期
     */
    "estabDate": string;

    /**
     * 最新规模（元，原始字符串）
     */
    "scale": string;

    /**
     * 交易状态（来自移动端详情接口；QDII 常有单日限额）
     * 申购状态（如 开放申购 / 暂停申购）
     */
    "subStatus": string;

    /**
     * 赎回状态
     */
    "redeemStatus": string;

    /**
     * 单日累计申购限额（原始字符串，空表示不限/未知）
     */
    "dayLimit": string;

    /** Creates a new FundDetail instance. */
    constructor($$source: Partial<FundDetail> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("rate" in $$source)) {
            this["rate"] = "";
        }
        if (!("minPurchase" in $$source)) {
            this["minPurchase"] = "";
        }
        if (!("netWorthTrend" in $$source)) {
            this["netWorthTrend"] = [];
        }
        if (!("acWorthTrend" in $$source)) {
            this["acWorthTrend"] = [];
        }
        if (!("maxDrawdown" in $$source)) {
            this["maxDrawdown"] = 0;
        }
        if (!("periodReturns" in $$source)) {
            this["periodReturns"] = [];
        }
        if (!("holdings" in $$source)) {
            this["holdings"] = [];
        }
        if (!("managers" in $$source)) {
            this["managers"] = [];
        }
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = 0;
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("indexName" in $$source)) {
            this["indexName"] = "";
        }
        if (!("riskLevel" in $$source)) {
            this["riskLevel"] = "";
        }
        if (!("estabDate" in $$source)) {
            this["estabDate"] = "";
        }
        if (!("scale" in $$source)) {
            this["scale"] = "";
        }
        if (!("subStatus" in $$source)) {
            this["subStatus"] = "";
        }
        if (!("redeemStatus" in $$source)) {
            this["redeemStatus"] = "";
        }
        if (!("dayLimit" in $$source)) {
            this["dayLimit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FundDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): FundDetail {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField8_0 = $$createType3;
        const $$createField9_0 = $$createType5;
        const $$createField10_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("netWorthTrend" in $$parsedSource) {
            $$parsedSource["netWorthTrend"] = $$createField5_0($$parsedSource["netWorthTrend"]);
        }
        if ("acWorthTrend" in $$parsedSource) {
            $$parsedSource["acWorthTrend"] = $$createField6_0($$parsedSource["acWorthTrend"]);
        }
        if ("periodReturns" in $$parsedSource) {
            $$parsedSource["periodReturns"] = $$createField8_0($$parsedSource["periodReturns"]);
        }
        if ("holdings" in $$parsedSource) {
            $$parsedSource["holdings"] = $$createField9_0($$parsedSource["holdings"]);
        }
        if ("managers" in $$parsedSource) {
            $$parsedSource["managers"] = $$createField10_0($$parsedSource["managers"]);
        }
        return new FundDetail($$parsedSource as Partial<FundDetail>);
    }
}

/**
 * FundEstimate 盘中估值。
 */
export class FundEstimate {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 上一交易日净值日期
     */
    "navDate": string;

    /**
     * 上一日单位净值
     */
    "prevNav": number;

    /**
     * 估算净值
     */
    "estimate": number;

    /**
     * 估算涨跌幅（%）
     */
    "estimateGrowth": number;

    /**
     * 估值时间
     */
    "estimateTime": string;

    /**
     * 是否有盘中估值（QDII 等为 false）
     */
    "hasEstimate": boolean;

    /** Creates a new FundEstimate instance. */
    constructor($$source: Partial<FundEstimate> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("navDate" in $$source)) {
            this["navDate"] = "";
        }
        if (!("prevNav" in $$source)) {
            this["prevNav"] = 0;
        }
        if (!("estimate" in $$source)) {
            this["estimate"] = 0;
        }
        if (!("estimateGrowth" in $$source)) {
            this["estimateGrowth"] = 0;
        }
        if (!("estimateTime" in $$source)) {
            this["estimateTime"] = "";
        }
        if (!("hasEstimate" in $$source)) {
            this["hasEstimate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FundEstimate instance from a string or object.
     */
    static createFrom($$source: any = {}): FundEstimate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FundEstimate($$parsedSource as Partial<FundEstimate>);
    }
}

/**
 * FundIndexItem 基金代码表条目（搜索索引）。
 */
export class FundIndexItem {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 基金类型（混合型/股票型/QDII/...）
     */
    "type": string;

    /**
     * 拼音首字母
     */
    "pinyinAbbr": string;

    /**
     * 拼音全拼
     */
    "pinyinFull": string;

    /** Creates a new FundIndexItem instance. */
    constructor($$source: Partial<FundIndexItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("pinyinAbbr" in $$source)) {
            this["pinyinAbbr"] = "";
        }
        if (!("pinyinFull" in $$source)) {
            this["pinyinFull"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FundIndexItem instance from a string or object.
     */
    static createFrom($$source: any = {}): FundIndexItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FundIndexItem($$parsedSource as Partial<FundIndexItem>);
    }
}

/**
 * FundIndexPage 基金索引搜索分页结果（排行页「就地搜索」用）。
 */
export class FundIndexPage {
    "items": FundIndexItem[];
    "total": number;

    /** Creates a new FundIndexPage instance. */
    constructor($$source: Partial<FundIndexPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FundIndexPage instance from a string or object.
     */
    static createFrom($$source: any = {}): FundIndexPage {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new FundIndexPage($$parsedSource as Partial<FundIndexPage>);
    }
}

/**
 * FundTheme 基金所属主题/概念（东财 ztjj 体系，TTYPE 形如 BKxxxxxx）。
 */
export class FundTheme {
    /**
     * 主题/板块代码（BKxxxxxx）
     */
    "code": string;

    /**
     * 主题/板块名称（如 CPO、电力设备）
     */
    "name": string;

    /** Creates a new FundTheme instance. */
    constructor($$source: Partial<FundTheme> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FundTheme instance from a string or object.
     */
    static createFrom($$source: any = {}): FundTheme {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FundTheme($$parsedSource as Partial<FundTheme>);
    }
}

/**
 * Holding 重仓股。
 */
export class Holding {
    /**
     * 股票代码
     */
    "stockCode": string;

    /**
     * 股票名称
     */
    "stockName": string;

    /**
     * 占净值比例（%）
     */
    "percent": number;

    /**
     * 个股当日涨跌幅（%）
     */
    "changePercent": number;

    /** Creates a new Holding instance. */
    constructor($$source: Partial<Holding> = {}) {
        if (!("stockCode" in $$source)) {
            this["stockCode"] = "";
        }
        if (!("stockName" in $$source)) {
            this["stockName"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("changePercent" in $$source)) {
            this["changePercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Holding instance from a string or object.
     */
    static createFrom($$source: any = {}): Holding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Holding($$parsedSource as Partial<Holding>);
    }
}

/**
 * IndexQuote 指数实时行情。
 */
export class IndexQuote {
    /**
     * 指数代码（如 sh000001）
     */
    "symbol": string;

    /**
     * 指数名称
     */
    "name": string;

    /**
     * 当前点位
     */
    "price": number;

    /**
     * 涨跌点数
     */
    "change": number;

    /**
     * 涨跌幅（%）
     */
    "changePercent": number;

    /** Creates a new IndexQuote instance. */
    constructor($$source: Partial<IndexQuote> = {}) {
        if (!("symbol" in $$source)) {
            this["symbol"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("price" in $$source)) {
            this["price"] = 0;
        }
        if (!("change" in $$source)) {
            this["change"] = 0;
        }
        if (!("changePercent" in $$source)) {
            this["changePercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexQuote instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexQuote {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexQuote($$parsedSource as Partial<IndexQuote>);
    }
}

/**
 * ManagerInfo 基金经理信息（含档案数据，来自 pingzhongdata）。
 */
export class ManagerInfo {
    /**
     * 经理 ID
     */
    "id": string;

    /**
     * 姓名
     */
    "name": string;

    /**
     * 照片 URL
     */
    "pic": string;

    /**
     * 星级（0-5）
     */
    "star": number;

    /**
     * 任职时间描述
     */
    "workTime": string;

    /**
     * 管理规模描述（如 532.96亿(23只基金)）
     */
    "fundSize": string;

    /**
     * 任期回报描述
     */
    "profit": string;

    /**
     * 能力评分雷达（经验值/收益率/跟踪误差/超额收益/管理规模）
     * 综合评分
     */
    "powerAvr": string;

    /**
     * 维度名称
     */
    "powerCategories": string[];

    /**
     * 各维度评分
     */
    "powerData": number[];

    /**
     * 任期收益对比（任期收益/同类平均/沪深300）
     * 对比项名称
     */
    "profitCategories": string[];

    /**
     * 对比项收益（%）
     */
    "profitData": number[];

    /** Creates a new ManagerInfo instance. */
    constructor($$source: Partial<ManagerInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("pic" in $$source)) {
            this["pic"] = "";
        }
        if (!("star" in $$source)) {
            this["star"] = 0;
        }
        if (!("workTime" in $$source)) {
            this["workTime"] = "";
        }
        if (!("fundSize" in $$source)) {
            this["fundSize"] = "";
        }
        if (!("profit" in $$source)) {
            this["profit"] = "";
        }
        if (!("powerAvr" in $$source)) {
            this["powerAvr"] = "";
        }
        if (!("powerCategories" in $$source)) {
            this["powerCategories"] = [];
        }
        if (!("powerData" in $$source)) {
            this["powerData"] = [];
        }
        if (!("profitCategories" in $$source)) {
            this["profitCategories"] = [];
        }
        if (!("profitData" in $$source)) {
            this["profitData"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagerInfo {
        const $$createField8_0 = $$createType10;
        const $$createField9_0 = $$createType11;
        const $$createField10_0 = $$createType10;
        const $$createField11_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("powerCategories" in $$parsedSource) {
            $$parsedSource["powerCategories"] = $$createField8_0($$parsedSource["powerCategories"]);
        }
        if ("powerData" in $$parsedSource) {
            $$parsedSource["powerData"] = $$createField9_0($$parsedSource["powerData"]);
        }
        if ("profitCategories" in $$parsedSource) {
            $$parsedSource["profitCategories"] = $$createField10_0($$parsedSource["profitCategories"]);
        }
        if ("profitData" in $$parsedSource) {
            $$parsedSource["profitData"] = $$createField11_0($$parsedSource["profitData"]);
        }
        return new ManagerInfo($$parsedSource as Partial<ManagerInfo>);
    }
}

/**
 * MarketBreadth 大盘涨跌分布。
 */
export class MarketBreadth {
    /**
     * 数据日期（yyyyMMdd）
     */
    "date": string;

    /**
     * 上涨家数
     */
    "upCount": number;

    /**
     * 下跌家数
     */
    "downCount": number;

    /**
     * 平盘家数
     */
    "flatCount": number;

    /**
     * 分布档位（按 level 升序）
     */
    "bins": BreadthBin[];

    /** Creates a new MarketBreadth instance. */
    constructor($$source: Partial<MarketBreadth> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("upCount" in $$source)) {
            this["upCount"] = 0;
        }
        if (!("downCount" in $$source)) {
            this["downCount"] = 0;
        }
        if (!("flatCount" in $$source)) {
            this["flatCount"] = 0;
        }
        if (!("bins" in $$source)) {
            this["bins"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketBreadth instance from a string or object.
     */
    static createFrom($$source: any = {}): MarketBreadth {
        const $$createField4_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bins" in $$parsedSource) {
            $$parsedSource["bins"] = $$createField4_0($$parsedSource["bins"]);
        }
        return new MarketBreadth($$parsedSource as Partial<MarketBreadth>);
    }
}

/**
 * MonitorState 监控调度状态（推送给前端展示）。
 */
export class MonitorState {
    /**
     * Idle / PreMarket / Trading / Lunch / NavConfirm
     */
    "phase": string;

    /**
     * 是否被用户暂停
     */
    "paused": boolean;

    /**
     * 下一次状态切换时间描述
     */
    "nextChange": string;

    /** Creates a new MonitorState instance. */
    constructor($$source: Partial<MonitorState> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("paused" in $$source)) {
            this["paused"] = false;
        }
        if (!("nextChange" in $$source)) {
            this["nextChange"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorState instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorState($$parsedSource as Partial<MonitorState>);
    }
}

/**
 * NavPage 历史净值分页结果。
 */
export class NavPage {
    "items": NavRecord[];
    "total": number;

    /** Creates a new NavPage instance. */
    constructor($$source: Partial<NavPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NavPage instance from a string or object.
     */
    static createFrom($$source: any = {}): NavPage {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new NavPage($$parsedSource as Partial<NavPage>);
    }
}

/**
 * NavRecord 历史净值记录。
 */
export class NavRecord {
    /**
     * 净值日期
     */
    "date": string;

    /**
     * 单位净值
     */
    "nav": number;

    /**
     * 累计净值
     */
    "accNav": number;

    /**
     * 日增长率（%）
     */
    "growth": number;

    /** Creates a new NavRecord instance. */
    constructor($$source: Partial<NavRecord> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("nav" in $$source)) {
            this["nav"] = 0;
        }
        if (!("accNav" in $$source)) {
            this["accNav"] = 0;
        }
        if (!("growth" in $$source)) {
            this["growth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NavRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): NavRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NavRecord($$parsedSource as Partial<NavRecord>);
    }
}

/**
 * NewsArticle 基金滚动资讯（来自 roll.eastmoney.com，指向完整文章页，正文需抓取页面）。
 */
export class NewsArticle {
    /**
     * 文章编号（URL 中的数字，前 8 位为 yyyyMMdd）
     */
    "id": string;

    /**
     * 标题
     */
    "title": string;

    /**
     * 文章页地址（finance/fund.eastmoney.com/a/{id}.html）
     */
    "url": string;

    /**
     * 发布日期（由文章编号推导，yyyy-MM-dd）
     */
    "time": string;

    /** Creates a new NewsArticle instance. */
    constructor($$source: Partial<NewsArticle> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewsArticle instance from a string or object.
     */
    static createFrom($$source: any = {}): NewsArticle {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewsArticle($$parsedSource as Partial<NewsArticle>);
    }
}

/**
 * NewsFlash 全球财经快讯（7×24 短讯，来自东财 getFastNewsList，summary 即完整正文）。
 */
export class NewsFlash {
    /**
     * 快讯唯一编号（接口 code 字段）
     */
    "id": string;

    /**
     * 标题
     */
    "title": string;

    /**
     * 正文（短讯本身即完整内容，含【标题】前缀）
     */
    "summary": string;

    /**
     * 发布时间（yyyy-MM-dd HH:mm:ss）
     */
    "time": string;

    /**
     * 是否重要（接口 titleColor != 0，通常标红）
     */
    "important": boolean;

    /**
     * 关联标的代码（如 0.159940）
     */
    "stocks": string[];

    /** Creates a new NewsFlash instance. */
    constructor($$source: Partial<NewsFlash> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("important" in $$source)) {
            this["important"] = false;
        }
        if (!("stocks" in $$source)) {
            this["stocks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewsFlash instance from a string or object.
     */
    static createFrom($$source: any = {}): NewsFlash {
        const $$createField5_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stocks" in $$parsedSource) {
            $$parsedSource["stocks"] = $$createField5_0($$parsedSource["stocks"]);
        }
        return new NewsFlash($$parsedSource as Partial<NewsFlash>);
    }
}

/**
 * PeriodReturn 基金阶段涨幅（含同类平均与同类排名，来自 FundMNPeriodIncrease）。
 */
export class PeriodReturn {
    /**
     * 周期键：Y/3Y/6Y/1N/2N/3N/JN/LN 等
     */
    "period": string;

    /**
     * 本基金涨跌幅（%）
     */
    "value": number;

    /**
     * 同类平均（%）
     */
    "avg": number;

    /**
     * 同类排名
     */
    "rank": number;

    /**
     * 同类数量
     */
    "count": number;

    /** Creates a new PeriodReturn instance. */
    constructor($$source: Partial<PeriodReturn> = {}) {
        if (!("period" in $$source)) {
            this["period"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("avg" in $$source)) {
            this["avg"] = 0;
        }
        if (!("rank" in $$source)) {
            this["rank"] = 0;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeriodReturn instance from a string or object.
     */
    static createFrom($$source: any = {}): PeriodReturn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PeriodReturn($$parsedSource as Partial<PeriodReturn>);
    }
}

/**
 * PortfolioSummary 持仓盈亏汇总。
 */
export class PortfolioSummary {
    /**
     * 总市值（盘中按估算净值计算）
     */
    "marketValue": number;

    /**
     * 当日预估收益
     */
    "todayProfit": number;

    /**
     * 当日预估收益率（%）
     */
    "todayPercent": number;

    /**
     * 累计收益
     */
    "totalProfit": number;

    /**
     * 持仓基金数
     */
    "positionCount": number;

    /** Creates a new PortfolioSummary instance. */
    constructor($$source: Partial<PortfolioSummary> = {}) {
        if (!("marketValue" in $$source)) {
            this["marketValue"] = 0;
        }
        if (!("todayProfit" in $$source)) {
            this["todayProfit"] = 0;
        }
        if (!("todayPercent" in $$source)) {
            this["todayPercent"] = 0;
        }
        if (!("totalProfit" in $$source)) {
            this["totalProfit"] = 0;
        }
        if (!("positionCount" in $$source)) {
            this["positionCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortfolioSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PortfolioSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortfolioSummary($$parsedSource as Partial<PortfolioSummary>);
    }
}

/**
 * Position 持仓记录（v1 每基金一条）。
 */
export class Position {
    "code": string;

    /**
     * 持有份额
     */
    "shares": number;

    /**
     * 持仓成本价
     */
    "costPrice": number;
    "updatedAt": number;

    /** Creates a new Position instance. */
    constructor($$source: Partial<Position> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("shares" in $$source)) {
            this["shares"] = 0;
        }
        if (!("costPrice" in $$source)) {
            this["costPrice"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     */
    static createFrom($$source: any = {}): Position {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position($$parsedSource as Partial<Position>);
    }
}

/**
 * ProfitHistoryPoint 组合每日收益历史点（全部持仓基金当日收益之和）。
 */
export class ProfitHistoryPoint {
    /**
     * 日期 yyyy-MM-dd
     */
    "date": string;

    /**
     * 当日收益（元）
     */
    "profit": number;

    /** Creates a new ProfitHistoryPoint instance. */
    constructor($$source: Partial<ProfitHistoryPoint> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("profit" in $$source)) {
            this["profit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfitHistoryPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfitHistoryPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfitHistoryPoint($$parsedSource as Partial<ProfitHistoryPoint>);
    }
}

/**
 * RankItem 基金排行条目。
 */
export class RankItem {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 净值日期
     */
    "date": string;

    /**
     * 单位净值
     */
    "nav": number;

    /**
     * 累计净值
     */
    "accNav": number;

    /**
     * 日涨幅（%）
     */
    "dayGrowth": number;

    /**
     * 周涨幅（%）
     */
    "weekGrowth": number;

    /**
     * 月涨幅（%）
     */
    "monthGrowth": number;

    /**
     * 近 3 月涨幅（%）
     */
    "month3": number;

    /**
     * 近 6 月涨幅（%）
     */
    "month6": number;

    /**
     * 近 1 年涨幅（%）
     */
    "year1": number;

    /**
     * 近 2 年涨幅（%）
     */
    "year2": number;

    /**
     * 近 3 年涨幅（%）
     */
    "year3": number;

    /**
     * 今年来涨幅（%）
     */
    "ytd": number;

    /**
     * 成立来涨幅（%）
     */
    "sinceStart": number;

    /**
     * 申购手续费（原始字符串，含 %，如 0.15%）
     */
    "fee": string;

    /**
     * 最新规模（元，来自移动端 FundMNFInfo 的 ENDNAV）
     */
    "scale": number;

    /** Creates a new RankItem instance. */
    constructor($$source: Partial<RankItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("nav" in $$source)) {
            this["nav"] = 0;
        }
        if (!("accNav" in $$source)) {
            this["accNav"] = 0;
        }
        if (!("dayGrowth" in $$source)) {
            this["dayGrowth"] = 0;
        }
        if (!("weekGrowth" in $$source)) {
            this["weekGrowth"] = 0;
        }
        if (!("monthGrowth" in $$source)) {
            this["monthGrowth"] = 0;
        }
        if (!("month3" in $$source)) {
            this["month3"] = 0;
        }
        if (!("month6" in $$source)) {
            this["month6"] = 0;
        }
        if (!("year1" in $$source)) {
            this["year1"] = 0;
        }
        if (!("year2" in $$source)) {
            this["year2"] = 0;
        }
        if (!("year3" in $$source)) {
            this["year3"] = 0;
        }
        if (!("ytd" in $$source)) {
            this["ytd"] = 0;
        }
        if (!("sinceStart" in $$source)) {
            this["sinceStart"] = 0;
        }
        if (!("fee" in $$source)) {
            this["fee"] = "";
        }
        if (!("scale" in $$source)) {
            this["scale"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RankItem instance from a string or object.
     */
    static createFrom($$source: any = {}): RankItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RankItem($$parsedSource as Partial<RankItem>);
    }
}

/**
 * RankPage 基金排行分页结果。
 */
export class RankPage {
    "items": RankItem[];
    "total": number;

    /** Creates a new RankPage instance. */
    constructor($$source: Partial<RankPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RankPage instance from a string or object.
     */
    static createFrom($$source: any = {}): RankPage {
        const $$createField0_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new RankPage($$parsedSource as Partial<RankPage>);
    }
}

/**
 * SectorItem 行业/概念板块行情。
 */
export class SectorItem {
    /**
     * 板块代码
     */
    "code": string;

    /**
     * 板块名称
     */
    "name": string;

    /**
     * 今日涨跌幅（%，f3）
     */
    "changePercent": number;

    /**
     * 近3月涨跌幅（%，f24=60日）
     */
    "month3": number;

    /**
     * 今年来涨跌幅（%，f25=年初至今）
     */
    "ytd": number;

    /**
     * 上涨家数
     */
    "upCount": number;

    /**
     * 下跌家数
     */
    "downCount": number;

    /**
     * 领涨股名称
     */
    "leadStock": string;

    /**
     * 主力资金净流入（元，f62）
     */
    "inflow": number;

    /**
     * 板块类别：industry / concept
     */
    "kind": string;

    /** Creates a new SectorItem instance. */
    constructor($$source: Partial<SectorItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("changePercent" in $$source)) {
            this["changePercent"] = 0;
        }
        if (!("month3" in $$source)) {
            this["month3"] = 0;
        }
        if (!("ytd" in $$source)) {
            this["ytd"] = 0;
        }
        if (!("upCount" in $$source)) {
            this["upCount"] = 0;
        }
        if (!("downCount" in $$source)) {
            this["downCount"] = 0;
        }
        if (!("leadStock" in $$source)) {
            this["leadStock"] = "";
        }
        if (!("inflow" in $$source)) {
            this["inflow"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SectorItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SectorItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SectorItem($$parsedSource as Partial<SectorItem>);
    }
}

/**
 * TopicItem 基金主题/板块条目（天天基金主题体系）。
 */
export class TopicItem {
    /**
     * 主题 ID（哈希串）
     */
    "id": string;

    /**
     * 主题名称
     */
    "name": string;

    /**
     * 近 1 年涨幅（%）
     */
    "year1Growth": number;

    /** Creates a new TopicItem instance. */
    constructor($$source: Partial<TopicItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("year1Growth" in $$source)) {
            this["year1Growth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicItem($$parsedSource as Partial<TopicItem>);
    }
}

/**
 * TrendPoint 净值走势点。
 */
export class TrendPoint {
    /**
     * 日期（YYYY-MM-DD）
     */
    "date": string;

    /**
     * 净值
     */
    "value": number;

    /**
     * 当日涨跌幅（%），累计净值走势中为 0
     */
    "growth": number;

    /** Creates a new TrendPoint instance. */
    constructor($$source: Partial<TrendPoint> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("growth" in $$source)) {
            this["growth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrendPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): TrendPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrendPoint($$parsedSource as Partial<TrendPoint>);
    }
}

/**
 * WatchGroup 自选分组。
 */
export class WatchGroup {
    "id": number;
    "name": string;
    "sort": number;

    /** Creates a new WatchGroup instance. */
    constructor($$source: Partial<WatchGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): WatchGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchGroup($$parsedSource as Partial<WatchGroup>);
    }
}

/**
 * WatchItem 自选条目。
 */
export class WatchItem {
    "code": string;
    "groupId": number;
    "sort": number;
    "pinned": boolean;
    "createdAt": number;

    /**
     * Name/Type 来自 fund_index 联查，便于前端直接展示
     */
    "name": string;
    "type": string;

    /** Creates a new WatchItem instance. */
    constructor($$source: Partial<WatchItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("groupId" in $$source)) {
            this["groupId"] = 0;
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchItem instance from a string or object.
     */
    static createFrom($$source: any = {}): WatchItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchItem($$parsedSource as Partial<WatchItem>);
    }
}

/**
 * XrayFundRef 持仓透视中某股票的来源基金。
 */
export class XrayFundRef {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 该股占基金净值比例（%）
     */
    "percent": number;

    /** Creates a new XrayFundRef instance. */
    constructor($$source: Partial<XrayFundRef> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new XrayFundRef instance from a string or object.
     */
    static createFrom($$source: any = {}): XrayFundRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new XrayFundRef($$parsedSource as Partial<XrayFundRef>);
    }
}

/**
 * XrayStock 持仓透视聚合后的股票暴露。
 */
export class XrayStock {
    /**
     * 股票代码
     */
    "stockCode": string;

    /**
     * 股票名称
     */
    "stockName": string;

    /**
     * 占组合权重（%，按持仓市值加权）
     */
    "weight": number;

    /**
     * 来源基金列表
     */
    "funds": XrayFundRef[];

    /** Creates a new XrayStock instance. */
    constructor($$source: Partial<XrayStock> = {}) {
        if (!("stockCode" in $$source)) {
            this["stockCode"] = "";
        }
        if (!("stockName" in $$source)) {
            this["stockName"] = "";
        }
        if (!("weight" in $$source)) {
            this["weight"] = 0;
        }
        if (!("funds" in $$source)) {
            this["funds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new XrayStock instance from a string or object.
     */
    static createFrom($$source: any = {}): XrayStock {
        const $$createField3_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("funds" in $$parsedSource) {
            $$parsedSource["funds"] = $$createField3_0($$parsedSource["funds"]);
        }
        return new XrayStock($$parsedSource as Partial<XrayStock>);
    }
}

// Private type creation functions
const $$createType0 = TrendPoint.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = PeriodReturn.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Holding.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ManagerInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = FundIndexItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = BreadthBin.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = NavRecord.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = RankItem.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = XrayFundRef.createFrom;
const $$createType19 = $Create.Array($$createType18);
