// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FundDetail 基金详情聚合数据。
 */
export class FundDetail {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 基金类型
     */
    "type": string;

    /**
     * 实际申购费率（%）
     */
    "rate": string;

    /**
     * 最小申购金额
     */
    "minPurchase": string;

    /**
     * 单位净值走势
     */
    "netWorthTrend": TrendPoint[];

    /**
     * 累计净值走势
     */
    "acWorthTrend": TrendPoint[];

    /**
     * 前十重仓股
     */
    "holdings": Holding[];

    /**
     * 现任基金经理
     */
    "managers": ManagerInfo[];

    /**
     * 数据抓取时间（Unix 秒）
     */
    "fetchedAt": number;

    /** Creates a new FundDetail instance. */
    constructor($$source: Partial<FundDetail> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("rate" in $$source)) {
            this["rate"] = "";
        }
        if (!("minPurchase" in $$source)) {
            this["minPurchase"] = "";
        }
        if (!("netWorthTrend" in $$source)) {
            this["netWorthTrend"] = [];
        }
        if (!("acWorthTrend" in $$source)) {
            this["acWorthTrend"] = [];
        }
        if (!("holdings" in $$source)) {
            this["holdings"] = [];
        }
        if (!("managers" in $$source)) {
            this["managers"] = [];
        }
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FundDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): FundDetail {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("netWorthTrend" in $$parsedSource) {
            $$parsedSource["netWorthTrend"] = $$createField5_0($$parsedSource["netWorthTrend"]);
        }
        if ("acWorthTrend" in $$parsedSource) {
            $$parsedSource["acWorthTrend"] = $$createField6_0($$parsedSource["acWorthTrend"]);
        }
        if ("holdings" in $$parsedSource) {
            $$parsedSource["holdings"] = $$createField7_0($$parsedSource["holdings"]);
        }
        if ("managers" in $$parsedSource) {
            $$parsedSource["managers"] = $$createField8_0($$parsedSource["managers"]);
        }
        return new FundDetail($$parsedSource as Partial<FundDetail>);
    }
}

/**
 * FundEstimate 盘中估值。
 */
export class FundEstimate {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 上一交易日净值日期
     */
    "navDate": string;

    /**
     * 上一日单位净值
     */
    "prevNav": number;

    /**
     * 估算净值
     */
    "estimate": number;

    /**
     * 估算涨跌幅（%）
     */
    "estimateGrowth": number;

    /**
     * 估值时间
     */
    "estimateTime": string;

    /**
     * 是否有盘中估值（QDII 等为 false）
     */
    "hasEstimate": boolean;

    /** Creates a new FundEstimate instance. */
    constructor($$source: Partial<FundEstimate> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("navDate" in $$source)) {
            this["navDate"] = "";
        }
        if (!("prevNav" in $$source)) {
            this["prevNav"] = 0;
        }
        if (!("estimate" in $$source)) {
            this["estimate"] = 0;
        }
        if (!("estimateGrowth" in $$source)) {
            this["estimateGrowth"] = 0;
        }
        if (!("estimateTime" in $$source)) {
            this["estimateTime"] = "";
        }
        if (!("hasEstimate" in $$source)) {
            this["hasEstimate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FundEstimate instance from a string or object.
     */
    static createFrom($$source: any = {}): FundEstimate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FundEstimate($$parsedSource as Partial<FundEstimate>);
    }
}

/**
 * FundIndexItem 基金代码表条目（搜索索引）。
 */
export class FundIndexItem {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 基金类型（混合型/股票型/QDII/...）
     */
    "type": string;

    /**
     * 拼音首字母
     */
    "pinyinAbbr": string;

    /**
     * 拼音全拼
     */
    "pinyinFull": string;

    /** Creates a new FundIndexItem instance. */
    constructor($$source: Partial<FundIndexItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("pinyinAbbr" in $$source)) {
            this["pinyinAbbr"] = "";
        }
        if (!("pinyinFull" in $$source)) {
            this["pinyinFull"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FundIndexItem instance from a string or object.
     */
    static createFrom($$source: any = {}): FundIndexItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FundIndexItem($$parsedSource as Partial<FundIndexItem>);
    }
}

/**
 * Holding 重仓股。
 */
export class Holding {
    /**
     * 股票代码
     */
    "stockCode": string;

    /**
     * 股票名称
     */
    "stockName": string;

    /**
     * 占净值比例（%）
     */
    "percent": number;

    /** Creates a new Holding instance. */
    constructor($$source: Partial<Holding> = {}) {
        if (!("stockCode" in $$source)) {
            this["stockCode"] = "";
        }
        if (!("stockName" in $$source)) {
            this["stockName"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Holding instance from a string or object.
     */
    static createFrom($$source: any = {}): Holding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Holding($$parsedSource as Partial<Holding>);
    }
}

/**
 * IndexQuote 指数实时行情。
 */
export class IndexQuote {
    /**
     * 指数代码（如 sh000001）
     */
    "symbol": string;

    /**
     * 指数名称
     */
    "name": string;

    /**
     * 当前点位
     */
    "price": number;

    /**
     * 涨跌点数
     */
    "change": number;

    /**
     * 涨跌幅（%）
     */
    "changePercent": number;

    /** Creates a new IndexQuote instance. */
    constructor($$source: Partial<IndexQuote> = {}) {
        if (!("symbol" in $$source)) {
            this["symbol"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("price" in $$source)) {
            this["price"] = 0;
        }
        if (!("change" in $$source)) {
            this["change"] = 0;
        }
        if (!("changePercent" in $$source)) {
            this["changePercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexQuote instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexQuote {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexQuote($$parsedSource as Partial<IndexQuote>);
    }
}

/**
 * ManagerInfo 基金经理信息。
 */
export class ManagerInfo {
    /**
     * 姓名
     */
    "name": string;

    /**
     * 任职时间描述
     */
    "workTime": string;

    /**
     * 任期回报描述
     */
    "profit": string;

    /** Creates a new ManagerInfo instance. */
    constructor($$source: Partial<ManagerInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("workTime" in $$source)) {
            this["workTime"] = "";
        }
        if (!("profit" in $$source)) {
            this["profit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManagerInfo($$parsedSource as Partial<ManagerInfo>);
    }
}

/**
 * MonitorState 监控调度状态（推送给前端展示）。
 */
export class MonitorState {
    /**
     * Idle / PreMarket / Trading / Lunch / NavConfirm
     */
    "phase": string;

    /**
     * 是否被用户暂停
     */
    "paused": boolean;

    /**
     * 下一次状态切换时间描述
     */
    "nextChange": string;

    /** Creates a new MonitorState instance. */
    constructor($$source: Partial<MonitorState> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("paused" in $$source)) {
            this["paused"] = false;
        }
        if (!("nextChange" in $$source)) {
            this["nextChange"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorState instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorState($$parsedSource as Partial<MonitorState>);
    }
}

/**
 * NavPage 历史净值分页结果。
 */
export class NavPage {
    "items": NavRecord[];
    "total": number;

    /** Creates a new NavPage instance. */
    constructor($$source: Partial<NavPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NavPage instance from a string or object.
     */
    static createFrom($$source: any = {}): NavPage {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new NavPage($$parsedSource as Partial<NavPage>);
    }
}

/**
 * NavRecord 历史净值记录。
 */
export class NavRecord {
    /**
     * 净值日期
     */
    "date": string;

    /**
     * 单位净值
     */
    "nav": number;

    /**
     * 累计净值
     */
    "accNav": number;

    /**
     * 日增长率（%）
     */
    "growth": number;

    /** Creates a new NavRecord instance. */
    constructor($$source: Partial<NavRecord> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("nav" in $$source)) {
            this["nav"] = 0;
        }
        if (!("accNav" in $$source)) {
            this["accNav"] = 0;
        }
        if (!("growth" in $$source)) {
            this["growth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NavRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): NavRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NavRecord($$parsedSource as Partial<NavRecord>);
    }
}

/**
 * PortfolioSummary 持仓盈亏汇总。
 */
export class PortfolioSummary {
    /**
     * 总市值（盘中按估算净值计算）
     */
    "marketValue": number;

    /**
     * 当日预估收益
     */
    "todayProfit": number;

    /**
     * 当日预估收益率（%）
     */
    "todayPercent": number;

    /**
     * 累计收益
     */
    "totalProfit": number;

    /**
     * 持仓基金数
     */
    "positionCount": number;

    /** Creates a new PortfolioSummary instance. */
    constructor($$source: Partial<PortfolioSummary> = {}) {
        if (!("marketValue" in $$source)) {
            this["marketValue"] = 0;
        }
        if (!("todayProfit" in $$source)) {
            this["todayProfit"] = 0;
        }
        if (!("todayPercent" in $$source)) {
            this["todayPercent"] = 0;
        }
        if (!("totalProfit" in $$source)) {
            this["totalProfit"] = 0;
        }
        if (!("positionCount" in $$source)) {
            this["positionCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortfolioSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PortfolioSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortfolioSummary($$parsedSource as Partial<PortfolioSummary>);
    }
}

/**
 * Position 持仓记录（v1 每基金一条）。
 */
export class Position {
    "code": string;

    /**
     * 持有份额
     */
    "shares": number;

    /**
     * 持仓成本价
     */
    "costPrice": number;
    "updatedAt": number;

    /** Creates a new Position instance. */
    constructor($$source: Partial<Position> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("shares" in $$source)) {
            this["shares"] = 0;
        }
        if (!("costPrice" in $$source)) {
            this["costPrice"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     */
    static createFrom($$source: any = {}): Position {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position($$parsedSource as Partial<Position>);
    }
}

/**
 * RankItem 基金排行条目。
 */
export class RankItem {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 净值日期
     */
    "date": string;

    /**
     * 单位净值
     */
    "nav": number;

    /**
     * 日涨幅（%）
     */
    "dayGrowth": number;

    /**
     * 周涨幅（%）
     */
    "weekGrowth": number;

    /**
     * 月涨幅（%）
     */
    "monthGrowth": number;

    /**
     * 近 3 月涨幅（%）
     */
    "month3": number;

    /**
     * 近 6 月涨幅（%）
     */
    "month6": number;

    /**
     * 近 1 年涨幅（%）
     */
    "year1": number;

    /**
     * 今年来涨幅（%）
     */
    "ytd": number;

    /** Creates a new RankItem instance. */
    constructor($$source: Partial<RankItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("nav" in $$source)) {
            this["nav"] = 0;
        }
        if (!("dayGrowth" in $$source)) {
            this["dayGrowth"] = 0;
        }
        if (!("weekGrowth" in $$source)) {
            this["weekGrowth"] = 0;
        }
        if (!("monthGrowth" in $$source)) {
            this["monthGrowth"] = 0;
        }
        if (!("month3" in $$source)) {
            this["month3"] = 0;
        }
        if (!("month6" in $$source)) {
            this["month6"] = 0;
        }
        if (!("year1" in $$source)) {
            this["year1"] = 0;
        }
        if (!("ytd" in $$source)) {
            this["ytd"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RankItem instance from a string or object.
     */
    static createFrom($$source: any = {}): RankItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RankItem($$parsedSource as Partial<RankItem>);
    }
}

/**
 * RankPage 基金排行分页结果。
 */
export class RankPage {
    "items": RankItem[];
    "total": number;

    /** Creates a new RankPage instance. */
    constructor($$source: Partial<RankPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RankPage instance from a string or object.
     */
    static createFrom($$source: any = {}): RankPage {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new RankPage($$parsedSource as Partial<RankPage>);
    }
}

/**
 * SectorItem 行业/概念板块行情。
 */
export class SectorItem {
    /**
     * 板块代码
     */
    "code": string;

    /**
     * 板块名称
     */
    "name": string;

    /**
     * 涨跌幅（%）
     */
    "changePercent": number;

    /**
     * 上涨家数
     */
    "upCount": number;

    /**
     * 下跌家数
     */
    "downCount": number;

    /**
     * 领涨股名称
     */
    "leadStock": string;

    /** Creates a new SectorItem instance. */
    constructor($$source: Partial<SectorItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("changePercent" in $$source)) {
            this["changePercent"] = 0;
        }
        if (!("upCount" in $$source)) {
            this["upCount"] = 0;
        }
        if (!("downCount" in $$source)) {
            this["downCount"] = 0;
        }
        if (!("leadStock" in $$source)) {
            this["leadStock"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SectorItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SectorItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SectorItem($$parsedSource as Partial<SectorItem>);
    }
}

/**
 * TrendPoint 净值走势点。
 */
export class TrendPoint {
    /**
     * 日期（YYYY-MM-DD）
     */
    "date": string;

    /**
     * 净值
     */
    "value": number;

    /**
     * 当日涨跌幅（%），累计净值走势中为 0
     */
    "growth": number;

    /** Creates a new TrendPoint instance. */
    constructor($$source: Partial<TrendPoint> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("growth" in $$source)) {
            this["growth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrendPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): TrendPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrendPoint($$parsedSource as Partial<TrendPoint>);
    }
}

/**
 * WatchGroup 自选分组。
 */
export class WatchGroup {
    "id": number;
    "name": string;
    "sort": number;

    /** Creates a new WatchGroup instance. */
    constructor($$source: Partial<WatchGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): WatchGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchGroup($$parsedSource as Partial<WatchGroup>);
    }
}

/**
 * WatchItem 自选条目。
 */
export class WatchItem {
    "code": string;
    "groupId": number;
    "sort": number;
    "pinned": boolean;
    "createdAt": number;

    /**
     * Name/Type 来自 fund_index 联查，便于前端直接展示
     */
    "name": string;
    "type": string;

    /** Creates a new WatchItem instance. */
    constructor($$source: Partial<WatchItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("groupId" in $$source)) {
            this["groupId"] = 0;
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchItem instance from a string or object.
     */
    static createFrom($$source: any = {}): WatchItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchItem($$parsedSource as Partial<WatchItem>);
    }
}

// Private type creation functions
const $$createType0 = TrendPoint.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Holding.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ManagerInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = NavRecord.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = RankItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
