// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Scheduler 监控调度器。
 */
export class Scheduler {

    /** Creates a new Scheduler instance. */
    constructor($$source: Partial<Scheduler> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scheduler instance from a string or object.
     */
    static createFrom($$source: any = {}): Scheduler {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Scheduler($$parsedSource as Partial<Scheduler>);
    }
}
