// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService AI 解读服务：基于设置中的 OpenAI 兼容配置，对财经新闻做快速解读。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Available 返回 AI 是否已启用且配置完整（前端用于决定是否展示「AI 解读」入口）。
 */
export function Available(): $CancellablePromise<boolean> {
    return $Call.ByID(1726811388);
}

/**
 * InterpretNews 对一条财经新闻（标题 + 正文）进行 AI 解读，返回解读文本。
 */
export function InterpretNews(title: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(843120617, title, content);
}
