// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService AI 解读服务：基于设置中的 OpenAI 兼容配置，对财经新闻做快速解读（支持流式输出）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * Available 返回 AI 是否已启用且配置完整（前端用于决定是否展示「AI 解读」入口）。
 */
export function Available(): $CancellablePromise<boolean> {
    return $Call.ByID(1726811388);
}

/**
 * InterpretNews 对一条财经新闻（标题 + 正文）进行 AI 解读，返回完整 Markdown 文本（非流式，保留作为兜底）。
 */
export function InterpretNews(title: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(843120617, title, content);
}

/**
 * InterpretNewsStream 流式解读：立即返回，随后通过 ai:chunk / ai:done / ai:error 事件向前端推送增量。
 * streamID 由前端生成，用于在多窗口/多次请求间区分事件归属。
 */
export function InterpretNewsStream(streamID: string, title: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2617288945, streamID, title, content);
}

/**
 * SetApp 注入 Wails 应用实例（装配时调用，用于流式解读经事件推送增量）。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1691817554, app);
}
