// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupService 数据备份与恢复服务：通过原生文件对话框导出/导入本地数据。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportData 导出全部数据到用户选择的 JSON 文件，返回保存路径（用户取消返回空字符串）。
 */
export function ExportData(): $CancellablePromise<string> {
    return $Call.ByID(2563904207);
}

/**
 * ImportData 从用户选择的备份文件恢复数据（整体替换自选/分组/持仓/收益历史并合并设置）。
 * 用户取消返回 nil。
 */
export function ImportData(): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByID(1733152464).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetOnChange 注入数据变更回调（不暴露给前端使用）。
 */
export function SetOnChange(fn: any): $CancellablePromise<void> {
    return $Call.ByID(3910226758, fn);
}

/**
 * SetWailsApplication 注入 Wails 应用实例（装配时调用，用于弹原生对话框）。
 */
export function SetWailsApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2932342375, app);
}

// Private type creation functions
const $$createType0 = $models.ImportResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
