// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FundService 基金数据服务：搜索、详情、历史净值、排行。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * EnsureFundIndex 确保基金代码表存在且未过期（应用启动时后台调用，不暴露给前端）。
 */
export function EnsureFundIndex(): $CancellablePromise<void> {
    return $Call.ByID(3610751999);
}

/**
 * GetFundDetail 获取基金详情（缓存优先，24h 过期后重新抓取）。
 */
export function GetFundDetail(code: string): $CancellablePromise<model$0.FundDetail | null> {
    return $Call.ByID(17137502, code).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFundRanking 获取基金排行。
 */
export function GetFundRanking(fundType: string, sortKey: string, pageIndex: number): $CancellablePromise<model$0.RankPage | null> {
    return $Call.ByID(1525782339, fundType, sortKey, pageIndex).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetNavHistory 获取历史净值（分页）。
 */
export function GetNavHistory(code: string, pageIndex: number, pageSize: number): $CancellablePromise<model$0.NavPage | null> {
    return $Call.ByID(4059753423, code, pageIndex, pageSize).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RefreshFundIndex 手动全量更新基金代码表（设置页调用）。
 */
export function RefreshFundIndex(): $CancellablePromise<void> {
    return $Call.ByID(3243024372);
}

/**
 * SearchFunds 本地搜索基金（代码/名称/拼音首字母/全拼）。
 */
export function SearchFunds(keyword: string, limit: number): $CancellablePromise<model$0.FundIndexItem[]> {
    return $Call.ByID(925186620, keyword, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.FundDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.RankPage.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.NavPage.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.FundIndexItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
