// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FundService 基金数据服务：搜索、详情、历史净值、排行。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * EnsureFundIndex 确保基金代码表存在且未过期（应用启动时后台调用，不暴露给前端）。
 */
export function EnsureFundIndex(): $CancellablePromise<void> {
    return $Call.ByID(3610751999);
}

/**
 * GetFundDetail 获取基金详情（缓存优先，24h 过期后重新抓取）。
 */
export function GetFundDetail(code: string): $CancellablePromise<model$0.FundDetail | null> {
    return $Call.ByID(17137502, code).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFundPerformance 批量补全一组基金的阶段收益（code → 收益），供搜索结果行内展示。
 * 今日涨跌与单位净值/净值日期取 fundgz（gszzl/dwjz/jzrq，单批并发），
 * 近1周~成立来各周期取移动端 FundMNPeriodIncrease（受限并发，同一接口一次取齐）；
 * 命中 3 分钟缓存直接返回，单只失败跳过不影响整体。
 */
export function GetFundPerformance(codes: string[]): $CancellablePromise<{ [_ in string]?: model$0.FundPerf }> {
    return $Call.ByID(1262016755, codes).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetFundRanking 获取基金排行（60s 内存缓存，配合前端翻页预取实现秒开）。sortType：desc/asc。
 */
export function GetFundRanking(fundType: string, sortKey: string, sortType: string, pageIndex: number): $CancellablePromise<model$0.RankPage | null> {
    return $Call.ByID(1525782339, fundType, sortKey, sortType, pageIndex).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetFundThemes 批量获取一组基金所属的主题/概念标签（code → 主题列表）。
 * 命中缓存（30 天 TTL）直接返回；缺失项以受限并发从东财搜索接口拉取并落库缓存，
 * 拉取失败的基金会被跳过（前端不展示标签），不影响整体返回。
 */
export function GetFundThemes(codes: string[]): $CancellablePromise<{ [_ in string]?: model$0.FundTheme[] }> {
    return $Call.ByID(436451321, codes).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetNavHistory 获取历史净值（分页）。
 */
export function GetNavHistory(code: string, pageIndex: number, pageSize: number): $CancellablePromise<model$0.NavPage | null> {
    return $Call.ByID(4059753423, code, pageIndex, pageSize).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * PreloadRanking 后台预热默认排行首页（应用启动时调用，进入页面秒开）。
 */
export function PreloadRanking(): $CancellablePromise<void> {
    return $Call.ByID(769203069);
}

/**
 * RefreshFundIndex 手动全量更新基金代码表（设置页调用）。
 */
export function RefreshFundIndex(): $CancellablePromise<void> {
    return $Call.ByID(3243024372);
}

/**
 * SearchFunds 本地搜索基金（代码/名称/拼音首字母/全拼），offset 用于滚动加载。
 */
export function SearchFunds(keyword: string, limit: number, offset: number): $CancellablePromise<model$0.FundIndexItem[]> {
    return $Call.ByID(925186620, keyword, limit, offset).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * SearchFundsPage 排行页就地搜索（本地索引分页，含总数）：匹配名称/代码/拼音，
 * 公司名通常为基金名前缀（如「易方达」可命中全部易方达系基金）。pageIndex 从 1 开始。
 */
export function SearchFundsPage(keyword: string, pageIndex: number): $CancellablePromise<model$0.FundIndexPage | null> {
    return $Call.ByID(215218647, keyword, pageIndex).then(($result: any) => {
        return $$createType14($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.FundDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.FundPerf.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = model$0.RankPage.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.FundTheme.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = model$0.NavPage.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = model$0.FundIndexItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = model$0.FundIndexPage.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
