// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FundService 基金数据服务：搜索、详情、历史净值、排行。
 * TODO(M1)：接入 internal/datasource/eastmoney 与 internal/storage 后实现真实逻辑，
 * 接口规格见 docs/DATA_SOURCES.md，任务拆解见 docs/ROADMAP.md 里程碑 M1/M2。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SearchFunds 按关键字搜索基金（代码/名称/拼音）。
 * TODO(M1)：基于本地 SQLite 基金代码表实现，当前为骨架占位。
 */
export function SearchFunds(keyword: string, limit: number): $CancellablePromise<$models.FundIndexItem[]> {
    return $Call.ByID(925186620, keyword, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FundIndexItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
