// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MarketService 市场行情服务：指数、板块、监控状态控制。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../internal/scheduler/models.js";

/**
 * GetEstimates 返回最近一轮自选估值缓存（窗口初始化用，后续靠事件推送）。
 */
export function GetEstimates(): $CancellablePromise<model$0.FundEstimate[]> {
    return $Call.ByID(2906683312).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetIndexQuotes 返回最近一轮指数行情缓存（窗口初始化用，后续靠事件推送）。
 */
export function GetIndexQuotes(): $CancellablePromise<model$0.IndexQuote[]> {
    return $Call.ByID(4091914254).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetMonitorState 返回当前监控状态。
 */
export function GetMonitorState(): $CancellablePromise<model$0.MonitorState> {
    return $Call.ByID(3357847774).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetSectors 拉取板块行情。kind：industry（行业）/ concept（概念）。
 */
export function GetSectors(kind: string): $CancellablePromise<model$0.SectorItem[]> {
    return $Call.ByID(1239119416, kind).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetTopicFunds 拉取某主题下的基金列表（服务端排序 + 分页）。
 * sortKey：NAVCHGRT/SYL_Z/SYL_Y/SYL_3Y/SYL_6Y/SYL_1N/SYL_JN；sortType：desc/asc。
 */
export function GetTopicFunds(topicID: string, sortKey: string, sortType: string, pageIndex: number): $CancellablePromise<model$0.RankPage | null> {
    return $Call.ByID(2767582740, topicID, sortKey, sortType, pageIndex).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetTopics 拉取基金主题列表（约 150 个，含近 1 年涨幅）。
 */
export function GetTopics(): $CancellablePromise<model$0.TopicItem[]> {
    return $Call.ByID(2510723945).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * PauseMonitor 暂停/恢复监控。
 */
export function PauseMonitor(paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(3729041663, paused);
}

/**
 * RefreshNow 手动触发一轮拉取。
 */
export function RefreshNow(): $CancellablePromise<void> {
    return $Call.ByID(216157250);
}

/**
 * SetScheduler 注入调度器（装配时调用，不暴露给前端使用）。
 */
export function SetScheduler(sched: scheduler$0.Scheduler | null): $CancellablePromise<void> {
    return $Call.ByID(699788778, sched);
}

// Private type creation functions
const $$createType0 = model$0.FundEstimate.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.IndexQuote.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.MonitorState.createFrom;
const $$createType5 = model$0.SectorItem.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = model$0.RankPage.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = model$0.TopicItem.createFrom;
const $$createType10 = $Create.Array($$createType9);
