// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MarketService 市场行情服务：指数、板块、监控状态控制。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../internal/scheduler/models.js";

/**
 * GetEstimates 返回最近一轮自选估值缓存（窗口初始化用，后续靠事件推送）。
 */
export function GetEstimates(): $CancellablePromise<model$0.FundEstimate[]> {
    return $Call.ByID(2906683312).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetIndexKline 按指数 secid 与周期（day/week/month）拉取 K 线（60s 内存缓存）。
 * 主源腾讯（A股/港股可取完整历史）；美股/北证 50 腾讯仅返回最新一根，自动回退东财 push2his。
 */
export function GetIndexKline(secid: string, period: string): $CancellablePromise<model$0.Kline[]> {
    return $Call.ByID(470939390, secid, period).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetIndexQuotes 返回最近一轮指数行情缓存（窗口初始化用，后续靠事件推送）。
 */
export function GetIndexQuotes(): $CancellablePromise<model$0.IndexQuote[]> {
    return $Call.ByID(4091914254).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetMarketBreadth 拉取大盘涨跌分布（按涨跌幅档位统计家数）。
 */
export function GetMarketBreadth(): $CancellablePromise<model$0.MarketBreadth | null> {
    return $Call.ByID(153537417).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetMarketCenterQuotes 拉取行情中心指数清单实时报价（5s 内存缓存，合并多窗口/多次事件触发的重复请求）。
 * 主源腾讯（稳定，A股/港股/美股全覆盖），失败回退东财 ulist.np。
 */
export function GetMarketCenterQuotes(): $CancellablePromise<model$0.MarketIndexQuote[]> {
    return $Call.ByID(1417542945).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetMonitorState 返回当前监控状态。
 */
export function GetMonitorState(): $CancellablePromise<model$0.MonitorState> {
    return $Call.ByID(3357847774).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetSectors 拉取板块行情（60s 内存缓存）。kind：industry（行业）/ concept（概念）。
 */
export function GetSectors(kind: string): $CancellablePromise<model$0.SectorItem[]> {
    return $Call.ByID(1239119416, kind).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetSectorMoneyFlow 拉取标准行业/概念板块的主力资金净流入排行（60s 内存缓存）。
 * kind：all / industry / concept。代码体系为东财标准板块码（BK0xxx，与 ztjj 主题码不同）。
 */
export function GetSectorMoneyFlow(kind: string): $CancellablePromise<model$0.SectorItem[]> {
    return $Call.ByID(2215174489, kind).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetThemeFunds 按主题（板块）代码拉取相关基金（服务端排序 + 分页；60s 内存缓存）。
 * bkCode 形如 BK000641（CPO）；sortKey：RZDF/SYL_Z/SYL_Y/SYL_3Y/SYL_6Y/SYL_1N/SYL_JN；sortType：desc/asc。
 */
export function GetThemeFunds(bkCode: string, sortKey: string, sortType: string, pageIndex: number): $CancellablePromise<model$0.RankPage | null> {
    return $Call.ByID(3321145818, bkCode, sortKey, sortType, pageIndex).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetTopicFunds 拉取某主题下的基金列表（服务端排序 + 分页；60s 内存缓存）。
 * sortKey：NAVCHGRT/SYL_Z/SYL_Y/SYL_3Y/SYL_6Y/SYL_1N/SYL_JN；sortType：desc/asc。
 */
export function GetTopicFunds(topicID: string, sortKey: string, sortType: string, pageIndex: number): $CancellablePromise<model$0.RankPage | null> {
    return $Call.ByID(2767582740, topicID, sortKey, sortType, pageIndex).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetTopics 拉取基金主题列表（约 150 个，含近 1 年涨幅；60s 内存缓存）。
 */
export function GetTopics(): $CancellablePromise<model$0.TopicItem[]> {
    return $Call.ByID(2510723945).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * PauseMonitor 暂停/恢复监控。
 */
export function PauseMonitor(paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(3729041663, paused);
}

/**
 * PreloadMarket 后台预热热门主题（默认概念板块，应用启动时调用，进入页面秒开）。
 */
export function PreloadMarket(): $CancellablePromise<void> {
    return $Call.ByID(791072036);
}

/**
 * RefreshNow 手动触发一轮拉取。
 */
export function RefreshNow(): $CancellablePromise<void> {
    return $Call.ByID(216157250);
}

/**
 * SetScheduler 注入调度器（装配时调用，不暴露给前端使用）。
 */
export function SetScheduler(sched: scheduler$0.Scheduler | null): $CancellablePromise<void> {
    return $Call.ByID(699788778, sched);
}

// Private type creation functions
const $$createType0 = model$0.FundEstimate.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.Kline.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.IndexQuote.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.MarketBreadth.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.MarketIndexQuote.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = model$0.MonitorState.createFrom;
const $$createType11 = model$0.SectorItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = model$0.RankPage.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = model$0.TopicItem.createFrom;
const $$createType16 = $Create.Array($$createType15);
