// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings 应用设置，前后端共享的结构。
 */
export class AppSettings {
    /**
     * Theme 主题：light / dark / system
     */
    "theme": string;

    /**
     * CompactMode 紧凑模式
     */
    "compactMode": boolean;

    /**
     * QuoteColorScheme 涨跌配色：cn（红涨绿跌）/ intl（绿涨红跌）
     */
    "quoteColorScheme": string;

    /**
     * RefreshIntervalSec 盘中估值刷新间隔（秒），可选 15/30/60
     */
    "refreshIntervalSec": number;

    /**
     * TrayTitleEnabled 托盘标题是否展示涨跌幅
     */
    "trayTitleEnabled": boolean;

    /**
     * CloseAction 主窗口关闭行为：hide（隐藏到托盘）/ quit（退出）
     */
    "closeAction": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("compactMode" in $$source)) {
            this["compactMode"] = false;
        }
        if (!("quoteColorScheme" in $$source)) {
            this["quoteColorScheme"] = "";
        }
        if (!("refreshIntervalSec" in $$source)) {
            this["refreshIntervalSec"] = 0;
        }
        if (!("trayTitleEnabled" in $$source)) {
            this["trayTitleEnabled"] = false;
        }
        if (!("closeAction" in $$source)) {
            this["closeAction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * FundIndexItem 基金代码表条目（搜索结果项）。
 */
export class FundIndexItem {
    /**
     * 基金代码
     */
    "code": string;

    /**
     * 基金名称
     */
    "name": string;

    /**
     * 基金类型（混合型/股票型/...）
     */
    "type": string;

    /**
     * 拼音首字母
     */
    "pinyinAbbr": string;

    /** Creates a new FundIndexItem instance. */
    constructor($$source: Partial<FundIndexItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("pinyinAbbr" in $$source)) {
            this["pinyinAbbr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FundIndexItem instance from a string or object.
     */
    static createFrom($$source: any = {}): FundIndexItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FundIndexItem($$parsedSource as Partial<FundIndexItem>);
    }
}
