// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings 应用设置，前后端共享的结构。
 */
export class AppSettings {
    /**
     * Theme 主题：light / dark / system
     */
    "theme": string;

    /**
     * CompactMode 紧凑模式
     */
    "compactMode": boolean;

    /**
     * QuoteColorScheme 涨跌配色：cn（红涨绿跌）/ intl（绿涨红跌）
     */
    "quoteColorScheme": string;

    /**
     * RefreshIntervalSec 盘中估值刷新间隔（秒），可选 15/30/60
     */
    "refreshIntervalSec": number;

    /**
     * TrayTitleTarget 托盘标题展示目标（指数 symbol 或基金代码，空为关闭）
     */
    "trayTitleTarget": string;

    /**
     * StealthMode 摸鱼模式：涨跌中性展示、金额隐藏
     */
    "stealthMode": boolean;

    /**
     * CloseAction 主窗口关闭行为：hide（隐藏到托盘）/ quit（退出）
     */
    "closeAction": string;

    /**
     * WatchedIndexes 订阅的指数列表
     */
    "watchedIndexes": string[];

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("compactMode" in $$source)) {
            this["compactMode"] = false;
        }
        if (!("quoteColorScheme" in $$source)) {
            this["quoteColorScheme"] = "";
        }
        if (!("refreshIntervalSec" in $$source)) {
            this["refreshIntervalSec"] = 0;
        }
        if (!("trayTitleTarget" in $$source)) {
            this["trayTitleTarget"] = "";
        }
        if (!("stealthMode" in $$source)) {
            this["stealthMode"] = false;
        }
        if (!("closeAction" in $$source)) {
            this["closeAction"] = "";
        }
        if (!("watchedIndexes" in $$source)) {
            this["watchedIndexes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("watchedIndexes" in $$parsedSource) {
            $$parsedSource["watchedIndexes"] = $$createField7_0($$parsedSource["watchedIndexes"]);
        }
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
