// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NewsService 财经资讯服务：快讯（由调度器定时拉取并推送）+ 基金滚动资讯（按需抓取）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../internal/scheduler/models.js";

/**
 * GetArticleContent 抓取资讯文章正文（弹窗展示与 AI 解读用，按 URL 长缓存）。
 */
export function GetArticleContent(url: string): $CancellablePromise<string> {
    return $Call.ByID(986571195, url);
}

/**
 * GetFlashNews 返回最近一轮快讯缓存（窗口初始化用，后续靠 news:flash 事件推送）。
 */
export function GetFlashNews(): $CancellablePromise<model$0.NewsFlash[]> {
    return $Call.ByID(2779054685).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetRollNews 拉取基金滚动资讯列表（完整文章，60s 内存缓存）。
 */
export function GetRollNews(): $CancellablePromise<model$0.NewsArticle[]> {
    return $Call.ByID(1655304784).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RefreshFlashNews 立即触发一轮快讯拉取（手动刷新）。
 */
export function RefreshFlashNews(): $CancellablePromise<void> {
    return $Call.ByID(2845365884);
}

/**
 * SetScheduler 注入调度器（装配时调用，不暴露给前端使用）。
 */
export function SetScheduler(sched: scheduler$0.Scheduler | null): $CancellablePromise<void> {
    return $Call.ByID(4040533553, sched);
}

// Private type creation functions
const $$createType0 = model$0.NewsFlash.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.NewsArticle.createFrom;
const $$createType3 = $Create.Array($$createType2);
