// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortfolioService 持仓与盈亏服务。
 * 计算口径见 docs/PRD.md 2.3 节：
 * 
 * 	持仓市值 = 份额 × 最新净值（盘中用估算净值）
 * 	当日预估收益 = 份额 × (估算净值 − 上一日净值)
 * 	累计收益 = 份额 × (最新净值 − 成本价)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../internal/scheduler/models.js";

/**
 * AddTransaction 记一笔交易流水（买入/卖出），自动重算持仓份额与加权成本。
 * 份额、净值需大于 0；金额留空（≤0）时按 份额 × 净值 自动计算。
 */
export function AddTransaction(code: string, date: string, kind: string, shares: number, price: number, amount: number, note: string): $CancellablePromise<void> {
    return $Call.ByID(3743489454, code, date, kind, shares, price, amount, note);
}

/**
 * DeleteDCAPlan 删除定投计划。
 */
export function DeleteDCAPlan(id: number): $CancellablePromise<void> {
    return $Call.ByID(568227051, id);
}

/**
 * DeletePosition 删除持仓：在单事务内清空该基金全部交易流水并移除派生缓存，保证原子一致。
 */
export function DeletePosition(code: string): $CancellablePromise<void> {
    return $Call.ByID(2367940775, code);
}

/**
 * DeleteTransaction 删除一笔交易流水并重算持仓。
 */
export function DeleteTransaction(id: number): $CancellablePromise<void> {
    return $Call.ByID(3602422716, id);
}

/**
 * GetPosition 查询某基金持仓（无持仓返回 nil）。
 */
export function GetPosition(code: string): $CancellablePromise<model$0.Position | null> {
    return $Call.ByID(1038004406, code).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetProfitHistory 返回组合每日收益历史（净值确认后落库的数据，升序，最多 days 天）。
 */
export function GetProfitHistory(days: number): $CancellablePromise<model$0.ProfitHistoryPoint[]> {
    return $Call.ByID(2860447045, days).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSummary 计算持仓盈亏汇总（基于最近一轮估值缓存）。
 */
export function GetSummary(): $CancellablePromise<model$0.PortfolioSummary | null> {
    return $Call.ByID(1904589935).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetXray 持仓透视：聚合自选基金的前十重仓股，分析股票层面暴露。
 * 有持仓时按持仓市值加权；完全无持仓时按等权计算。
 */
export function GetXray(): $CancellablePromise<model$0.XrayStock[]> {
    return $Call.ByID(1687472949).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListClearedCodes 返回「已清仓」的基金代码（曾持有、当前份额为 0），供各列表展示清仓状态。
 */
export function ListClearedCodes(): $CancellablePromise<string[]> {
    return $Call.ByID(2605793697).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListDCAPlans 返回全部定投计划。
 */
export function ListDCAPlans(): $CancellablePromise<model$0.DCAPlan[]> {
    return $Call.ByID(314129507).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListPositions 返回全部持仓。
 */
export function ListPositions(): $CancellablePromise<model$0.Position[]> {
    return $Call.ByID(153802093).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListTransactions 返回某基金的交易流水（按日期升序）。
 */
export function ListTransactions(code: string): $CancellablePromise<model$0.PositionTxn[]> {
    return $Call.ByID(2900775846, code).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SetDCAPlanEnabled 启用/停用定投计划。
 */
export function SetDCAPlanEnabled(id: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1111399109, id, enabled);
}

/**
 * SetDetailProvider 注入基金详情读取函数（持仓透视需要读取详情缓存，不暴露给前端使用）。
 */
export function SetDetailProvider(fn: any): $CancellablePromise<void> {
    return $Call.ByID(635106265, fn);
}

/**
 * SetOnChange 注入持仓变更回调（不暴露给前端使用）。
 */
export function SetOnChange(fn: any): $CancellablePromise<void> {
    return $Call.ByID(2039036768, fn);
}

/**
 * SetScheduler 注入调度器（装配时调用，不暴露给前端使用）。
 */
export function SetScheduler(sched: scheduler$0.Scheduler | null): $CancellablePromise<void> {
    return $Call.ByID(2642255170, sched);
}

/**
 * UpsertDCAPlan 新增/更新定投计划（ID>0 为更新），返回写入后的计划 id。
 */
export function UpsertDCAPlan(plan: model$0.DCAPlan): $CancellablePromise<number> {
    return $Call.ByID(106173427, plan);
}

/**
 * UpsertPosition 设为基准持仓：清空该基金现有流水，写入一笔基准买入后重算缓存。
 * 供「直接编辑份额/成本」的手动覆盖入口使用，避免与流水模型冲突。
 */
export function UpsertPosition(code: string, shares: number, costPrice: number): $CancellablePromise<void> {
    return $Call.ByID(3257881231, code, shares, costPrice);
}

// Private type creation functions
const $$createType0 = model$0.Position.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ProfitHistoryPoint.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.PortfolioSummary.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.XrayStock.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = model$0.DCAPlan.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($$createType0);
const $$createType12 = model$0.PositionTxn.createFrom;
const $$createType13 = $Create.Array($$createType12);
