// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortfolioService 持仓与盈亏服务。
 * 计算口径见 docs/PRD.md 2.3 节：
 *   持仓市值 = 份额 × 最新净值（盘中用估算净值）
 *   当日预估收益 = 份额 × (估算净值 − 上一日净值)
 *   累计收益 = 份额 × (最新净值 − 成本价)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../internal/scheduler/models.js";

/**
 * DeletePosition 删除持仓。
 */
export function DeletePosition(code: string): $CancellablePromise<void> {
    return $Call.ByID(2367940775, code);
}

/**
 * GetPosition 查询某基金持仓（无持仓返回 nil）。
 */
export function GetPosition(code: string): $CancellablePromise<model$0.Position | null> {
    return $Call.ByID(1038004406, code).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetProfitHistory 返回组合每日收益历史（净值确认后落库的数据，升序，最多 days 天）。
 */
export function GetProfitHistory(days: number): $CancellablePromise<model$0.ProfitHistoryPoint[]> {
    return $Call.ByID(2860447045, days).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSummary 计算持仓盈亏汇总（基于最近一轮估值缓存）。
 */
export function GetSummary(): $CancellablePromise<model$0.PortfolioSummary | null> {
    return $Call.ByID(1904589935).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetXray 持仓透视：聚合自选基金的前十重仓股，分析股票层面暴露。
 * 有持仓时按持仓市值加权；完全无持仓时按等权计算。
 */
export function GetXray(): $CancellablePromise<model$0.XrayStock[]> {
    return $Call.ByID(1687472949).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListPositions 返回全部持仓。
 */
export function ListPositions(): $CancellablePromise<model$0.Position[]> {
    return $Call.ByID(153802093).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SetDetailProvider 注入基金详情读取函数（持仓透视需要读取详情缓存，不暴露给前端使用）。
 */
export function SetDetailProvider(fn: any): $CancellablePromise<void> {
    return $Call.ByID(635106265, fn);
}

/**
 * SetOnChange 注入持仓变更回调（不暴露给前端使用）。
 */
export function SetOnChange(fn: any): $CancellablePromise<void> {
    return $Call.ByID(2039036768, fn);
}

/**
 * SetScheduler 注入调度器（装配时调用，不暴露给前端使用）。
 */
export function SetScheduler(sched: scheduler$0.Scheduler | null): $CancellablePromise<void> {
    return $Call.ByID(2642255170, sched);
}

/**
 * UpsertPosition 录入/更新持仓。
 */
export function UpsertPosition(code: string, shares: number, costPrice: number): $CancellablePromise<void> {
    return $Call.ByID(3257881231, code, shares, costPrice);
}

// Private type creation functions
const $$createType0 = model$0.Position.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ProfitHistoryPoint.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.PortfolioSummary.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.XrayStock.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($$createType0);
