// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置服务：负责设置的读取与持久化（JSON 文件）。
 * TODO(M1)：迁移到 SQLite settings 表（见 docs/TECH_DESIGN.md 第 5 节）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get 返回当前设置。
 */
export function Get(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(202649858).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Update 整体更新设置并持久化。
 */
export function Update(next: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1269253007, next);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
