// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置服务：持久化到 SQLite settings 表。
 * 同时实现 scheduler.SettingsProvider 接口供调度器读取。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EstimateInterval 盘中估值轮询间隔。
 */
export function EstimateInterval(): $CancellablePromise<time$0.Duration> {
    return $Call.ByID(3355744865);
}

/**
 * Get 返回当前设置。
 */
export function Get(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(202649858).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetOnChange 注入设置变更回调（不暴露给前端使用）。
 */
export function SetOnChange(fn: any): $CancellablePromise<void> {
    return $Call.ByID(2902219603, fn);
}

/**
 * StealthMode 摸鱼模式开关。
 */
export function StealthMode(): $CancellablePromise<boolean> {
    return $Call.ByID(1029807762);
}

/**
 * TrayTitleTarget 托盘标题展示目标。
 */
export function TrayTitleTarget(): $CancellablePromise<string> {
    return $Call.ByID(1449157989);
}

/**
 * Update 整体更新设置并持久化。
 */
export function Update(next: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1269253007, next);
}

/**
 * WatchedIndexes 订阅的指数代码。
 */
export function WatchedIndexes(): $CancellablePromise<string[]> {
    return $Call.ByID(2443128524).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
const $$createType1 = $Create.Array($Create.Any);
