// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WatchlistService 自选与分组管理服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../internal/scheduler/models.js";

/**
 * AddItem 添加自选并立即刷新估值。
 */
export function AddItem(code: string, groupID: number): $CancellablePromise<void> {
    return $Call.ByID(3839228092, code, groupID);
}

/**
 * CreateGroup 新建分组。
 */
export function CreateGroup(name: string): $CancellablePromise<model$0.WatchGroup | null> {
    return $Call.ByID(2062280127, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteGroup 删除分组及其条目。
 */
export function DeleteGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(3585338410, id);
}

/**
 * ListGroups 返回全部分组。
 */
export function ListGroups(): $CancellablePromise<model$0.WatchGroup[]> {
    return $Call.ByID(2825944000).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListItems 返回某分组下的自选条目。
 */
export function ListItems(groupID: number): $CancellablePromise<model$0.WatchItem[]> {
    return $Call.ByID(3162395076, groupID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * MoveItem 将自选从源分组移动到目标分组。
 */
export function MoveItem(code: string, fromGroupID: number, toGroupID: number): $CancellablePromise<void> {
    return $Call.ByID(3531129398, code, fromGroupID, toGroupID);
}

/**
 * RemoveItem 移除自选。
 */
export function RemoveItem(code: string, groupID: number): $CancellablePromise<void> {
    return $Call.ByID(3287145023, code, groupID);
}

/**
 * RenameGroup 重命名分组。
 */
export function RenameGroup(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3331012125, id, name);
}

/**
 * SetOnChange 注入自选变更回调（不暴露给前端使用）。
 */
export function SetOnChange(fn: any): $CancellablePromise<void> {
    return $Call.ByID(3010620241, fn);
}

/**
 * SetScheduler 注入调度器（装配时调用，不暴露给前端使用）。
 */
export function SetScheduler(sched: scheduler$0.Scheduler | null): $CancellablePromise<void> {
    return $Call.ByID(3433708197, sched);
}

// Private type creation functions
const $$createType0 = model$0.WatchGroup.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = model$0.WatchItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
