// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 多窗口管理服务：负责主窗口、托盘面板窗口、基金详情独立窗口的创建与复用。
 * 窗口规格见 docs/TECH_DESIGN.md 第 6 节。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * CreateMainWindow 创建主窗口（应用启动时由 runner 调用一次）。
 */
export function CreateMainWindow(): $CancellablePromise<application$0.WebviewWindow | null> {
    return $Call.ByID(3088522046).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateTrayPanelWindow 创建托盘监控面板窗口（启动时创建但保持隐藏，点击托盘图标弹出）。
 */
export function CreateTrayPanelWindow(): $CancellablePromise<application$0.WebviewWindow | null> {
    return $Call.ByID(2184235559).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * HideMainWindow 隐藏主窗口（前端自绘关闭按钮调用）。
 */
export function HideMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(1771363934);
}

/**
 * OpenDetailWindow 打开基金详情独立窗口；同一基金代码复用已存在的窗口。
 */
export function OpenDetailWindow(code: string): $CancellablePromise<void> {
    return $Call.ByID(4018928994, code);
}

/**
 * QuitApp 退出应用（托盘菜单/设置页调用）。
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(1669154047);
}

/**
 * SetWailsApplication 注入 Wails 应用实例（在 runner 中调用，不暴露给前端使用）。
 */
export function SetWailsApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3738403669, app);
}

/**
 * ShowMainWindow 显示并聚焦主窗口（托盘菜单/面板调用）。
 */
export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(72738639);
}

// Private type creation functions
const $$createType0 = application$0.WebviewWindow.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
